### ISSUE TITLE
run hexo server  throw TypeError

### ISSUE THREAD

**Issue by youxiachai** [hexojs/hexo-server#2]
I migrating 2 -> 3
https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0

when i run 
``` bash
hexo server
```

throw

``` bash
E:\ProjectGitHub\Blogs\youxiachaiblog>hexo server
[error] TypeError: Cannot read property 'server' of undefined
TypeError: Cannot read property 'server' of undefined
    at server (E:\ProjectGitHub\Blogs\youxiachaiblog\node_modules\hexo-server\lib\server.js:9:39)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\lib\core\index.js:227:7
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at Hexo.call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\lib\core\index.js:226
:7)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\lib\init.js:64:10
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\async.js:
157:25
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\async.js:
254:17
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\async.js:
157:25
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\async.js:
251:21
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\async.js:
615:34
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\lib\loaders\scripts.js:10:24
    at Object.cb [as oncomplete] (fs.js:168:19)
```

**Comment by youxiachai** [comment]
my hexo version not right
