### ISSUE TITLE
Crash when callin hexo server -o

### ISSUE THREAD

**Issue by tomap** [hexojs/hexo-server#42]
Hi,

I have the following crash when I call ```hexo server -o```:
```
INFO  Hexo is running at http://localhost:4000. Press Ctrl+C to stop.
(node:23889) UnhandledPromiseRejectionWarning: Error: Expected a `target`
    at module.exports (/Users/thomas/Documents/hexo/tpi/node_modules/opn/index.js:9:25)
    at /Users/thomas/Documents/hexo/tpi/node_modules/hexo-server/lib/server.js:37:7
    at tryCatcher (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/thomas/Documents/hexo/tpi/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
(node:23889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23889) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I believe it is due to this commit:
https://github.com/hexojs/hexo-server/commit/dd31ccb478420ea2c8dd43c182e1fcbb65627d11#diff-c945a46d13b34fcaff544d966cffcabaL30

You should do:
https://github.com/hexojs/hexo-server/blob/master/lib/server.js#L37
```open(addrString)```
instead of
```open(addr)```

Regards,

Thomas

**Comment by demurgos** [comment]
Thanks for reporting this issue.

Could you send a PR for this issue if you have some time?
