### ISSUE TITLE
URI malformed and no reason.

### ISSUE THREAD

**Issue by flyinguard** [hexojs/hexo-server#9]
MacBook-Pro:xxx lionvii$ hexo s
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
URIError: URI malformed
    at decodeURIComponent (native)
    at /Users/lionvii/xxx/node_modules/hexo-server/lib/middlewares/route.js:18:50
    at call (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/proto.js:210:7)
    at next (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/proto.js:154:5)
    at compression (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/compression/index.js:212:5)
    at call (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/proto.js:210:7)
    at next (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/proto.js:154:5)
    at /Users/lionvii/xxx/node_modules/hexo-server/lib/middlewares/header.js:6:5
    at call (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/proto.js:210:7)
    at next (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/proto.js:154:5)
    at Function.app.handle (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/proto.js:157:3)
    at Server.app (/Users/lionvii/xxx/node_modules/hexo-server/node_modules/connect/lib/connect.js:28:37)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

**Comment by lionvii** [comment]
MacBook-Pro:xxx lionvii$ hexo --version
hexo: 3.0.0
os: Darwin 14.1.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l

**Comment by lionvii** [comment]
MacBook-Pro:xxx lionvii$ hexo --version
hexo: 3.0.0
os: Darwin 14.1.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l

**Comment by lionvii** [comment]
MacBook-Pro:xxx lionvii$ hexo --version
hexo: 3.0.0
os: Darwin 14.1.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l

**Comment by leesei** [comment]
Did you change `permalink` in config?

**Comment by NoahDragon** [comment]
As haven't got any feed back for more than half year. I will close this issue.

Feel free to reopen it, if the issue still there.
